version: '3.8'

services:
  postgres-test:
    image: pgvector/pgvector:pg16
    container_name: postgres-pgvector-test
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=floware
    ports:
      - '5433:5432'
    volumes:
      - pgvector_test_data:/var/lib/postgresql/data
    shm_size: '1gb'

volumes:
  pgvector_test_data:
    driver: local