"""create app table

Revision ID: ac10dc573599
Revises: 521ae4960bcf
Create Date: 2025-08-21 12:51:55.818597

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac10dc573599'
down_revision = '521ae4960bcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'app',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('app_name', sa.String(), nullable=False),
        sa.Column('app_url', sa.String(), nullable=False),
        sa.Column('app_secret', sa.String(), nullable=False),
        sa.Column('app_key', sa.String(), nullable=False),
        sa.Column('deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_app_id'), 'app', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_id'), table_name='app')
    op.drop_table('app')
    # ### end Alembic commands ###
