"""
Language detection and configuration constants

Contains keyword mappings and instructions for multi-language support
"""

from typing import Dict, List


# Language keyword mappings for detection
LANGUAGE_KEYWORDS: Dict[str, List[str]] = {
    'en': ['english', 'inglés', 'inglese'],
    'es': ['spanish', 'español', 'espanol', 'castellano'],
    'hi': ['hindi', 'हिंदी', 'हिन्दी'],
    'te': ['telugu', 'తెలుగు'],
    'ta': ['tamil', 'தமிழ்'],
    'kn': ['kannada', 'ಕನ್ನಡ'],
    'ml': ['malayalam', 'മലയാളം'],
    'mr': ['marathi', 'मराठी'],
    'gu': ['gujarati', 'ગુજરાતી'],
    'pa': ['punjabi', 'ਪੰਜਾಬੀ'],
    'bn': ['bengali', 'বাংলা'],
    'zh': ['chinese', 'mandarin', '中文', '普通话'],
    'ja': ['japanese', '日本語'],
    'ko': ['korean', '한국어'],
    'fr': ['french', 'français', 'francais'],
    'de': ['german', 'deutsch'],
    'it': ['italian', 'italiano'],
    'pt': ['portuguese', 'português', 'portugues'],
    'ru': ['russian', 'русский'],
    'ar': ['arabic', 'عربي', 'العربية'],
    'tr': ['turkish', 'türkçe', 'turkce'],
    'fil': ['filipino', 'pilipino', 'tagalog'],
    'tl': ['tagalog', 'filipino'],
    'fi': ['finnish', 'suomi'],
    'cs': ['czech', 'čeština', 'cestina'],
    'da': ['danish', 'dansk'],
    'el': ['greek', 'ελληνικά', 'ellinika'],
    'he': ['hebrew', 'עברית', 'ivrit'],
    'hr': ['croatian', 'hrvatski'],
    'hu': ['hungarian', 'magyar'],
    'id': ['indonesian', 'bahasa indonesia'],
    'ka': ['georgian', 'ქართული', 'kartuli'],
    'ms': ['malay', 'bahasa melayu'],
    'nl': ['dutch', 'nederlands'],
    'no': ['norwegian', 'norsk'],
    'pl': ['polish', 'polski'],
    'ro': ['romanian', 'română', 'romana'],
    'sk': ['slovak', 'slovenčina', 'slovencina'],
    'sv': ['swedish', 'svenska'],
    'th': ['thai', 'ภาษาไทย', 'phasa thai'],
    'uk': ['ukrainian', 'українська', 'ukrainska'],
    'vi': ['vietnamese', 'tiếng việt', 'tieng viet'],
}

# Language-specific LLM instructions
LANGUAGE_INSTRUCTIONS: Dict[str, str] = {
    'en': 'Respond in English.',
    'es': 'Respond in Spanish (Responde en español).',
    'hi': 'Respond in Hindi (हिंदी में जवाब दें).',
    'te': 'Respond in Telugu (తెలుగులో సమాధానం ఇవ్వండి).',
    'ta': 'Respond in Tamil (தமிழில் பதிலளிக்கவும்).',
    'kn': 'Respond in Kannada (ಕನ್ನಡದಲ್ಲಿ ಉತ್ತರಿಸಿ).',
    'ml': 'Respond in Malayalam (മലയാളത്തിൽ മറുപടി നൽകുക).',
    'mr': 'Respond in Marathi (मराठीत उत्तर द्या).',
    'gu': 'Respond in Gujarati (ગુજરાતીમાં જવાબ આપો).',
    'pa': 'Respond in Punjabi (ਪੰਜਾਬੀ ਵਿੱਚ ਜਵਾਬ ਦਿਓ).',
    'bn': 'Respond in Bengali (বাংলায় উত্তর দিন).',
    'zh': 'Respond in Chinese (用中文回复).',
    'ja': 'Respond in Japanese (日本語で応答してください).',
    'ko': 'Respond in Korean (한국어로 답변하세요).',
    'fr': 'Respond in French (Répondez en français).',
    'de': 'Respond in German (Auf Deutsch antworten).',
    'it': 'Respond in Italian (Rispondi in italiano).',
    'pt': 'Respond in Portuguese (Responda em português).',
    'ru': 'Respond in Russian (Отвечайте на русском).',
    'ar': 'Respond in Arabic (الرد بالعربية).',
    'tr': 'Respond in Turkish (Türkçe cevap verin).',
    'fil': 'Respond in Filipino (Tumugon sa Filipino).',
    'tl': 'Respond in Tagalog (Tumugon sa Tagalog).',
    'fi': 'Respond in Finnish (Vastaa suomeksi).',
    'cs': 'Respond in Czech (Odpovězte česky).',
    'da': 'Respond in Danish (Svar på dansk).',
    'el': 'Respond in Greek (Απαντήστε στα ελληνικά).',
    'he': 'Respond in Hebrew (ענה בעברית).',
    'hr': 'Respond in Croatian (Odgovorite na hrvatskom).',
    'hu': 'Respond in Hungarian (Válaszoljon magyarul).',
    'id': 'Respond in Indonesian (Jawab dalam bahasa Indonesia).',
    'ka': 'Respond in Georgian (უპასუხეთ ქართულად).',
    'ms': 'Respond in Malay (Jawab dalam bahasa Melayu).',
    'nl': 'Respond in Dutch (Antwoord in het Nederlands).',
    'no': 'Respond in Norwegian (Svar på norsk).',
    'pl': 'Respond in Polish (Odpowiedz po polsku).',
    'ro': 'Respond in Romanian (Răspundeți în română).',
    'sk': 'Respond in Slovak (Odpovedzte po slovensky).',
    'sv': 'Respond in Swedish (Svara på svenska).',
    'th': 'Respond in Thai (ตอบเป็นภาษาไทย).',
    'uk': 'Respond in Ukrainian (Відповідайте українською).',
    'vi': 'Respond in Vietnamese (Trả lời bằng tiếng Việt).',
}
