#!/bin/bash

# Generate RSA key pair for JWT authentication
# Output is base64-encoded for use in .env file

set -e

echo "Generating RSA key pair for JWT authentication..."

# Generate private key
ssh-keygen -t rsa -b 2048 -m PEM -f private.pem -N "" -q

# Restrict permissions on private key immediately
chmod 600 private.pem

# Extract public key
openssl rsa -in private.pem -pubout -out public.pem 2>/dev/null

echo ""
echo "Keys generated successfully! Copy these lines to your .env file:"
echo ""
echo "# JWT Keys (generated by scripts/generate-keys.sh)"

# macOS uses base64 without -w flag, Linux uses -w 0
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "PRIVATE_KEY=$(base64 < private.pem | tr -d '\n')"
    echo "PUBLIC_KEY=$(base64 < public.pem | tr -d '\n')"
else
    echo "PRIVATE_KEY=$(base64 -w 0 < private.pem)"
    echo "PUBLIC_KEY=$(base64 -w 0 < public.pem)"
fi

# Clean up temporary files
rm private.pem public.pem

echo ""
echo "Temporary key files removed. Keys are ready to use!"
