"""Create a baseline migrations

Revision ID: f6b7ce8e5b03
Revises:
Create Date: 2024-12-04 13:26:56.138406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f6b7ce8e5b03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'document',
        sa.Column('document_id', sa.String(), nullable=False),
        sa.Column('document_name', sa.String(), nullable=False),
        sa.Column('last_update_timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('document_id'),
    )
    op.create_index(
        op.f('ix_document_document_id'), 'document', ['document_id'], unique=False
    )
    op.create_table(
        'email',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('thread_id', sa.String(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('synced_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_email_id'), 'email', ['id'], unique=False)
    op.create_table(
        'oauth_credential',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('access_token', sa.String(), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=False),
        sa.Column('token_uri', sa.String(), nullable=True),
        sa.Column('client_id', sa.String(), nullable=True),
        sa.Column('client_secret', sa.String(), nullable=True),
        sa.Column('scopes', sa.JSON(), nullable=False),
        sa.Column('expiry', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_oauth_credential_id'), 'oauth_credential', ['id'], unique=False
    )
    op.create_table(
        'role',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table(
        'saml_config',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('entity_id', sa.String(), nullable=False),
        sa.Column('sso_url', sa.String(), nullable=False),
        sa.Column('slo_url', sa.String(), nullable=True),
        sa.Column('x509_certificate', sa.String(), nullable=False),
        sa.Column('name_id_format', sa.String(), nullable=True),
        sa.Column('metadata_xml', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_saml_config_is_active'), 'saml_config', ['is_active'], unique=False
    )
    op.create_table(
        'task',
        sa.Column('message_id', sa.String(), nullable=False),
        sa.Column('thread_id', sa.String(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('sender', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('priority', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('message_id'),
    )
    op.create_table(
        'team',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table(
        'user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('team_id', sa.String(), nullable=True),
        sa.Column('role_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_table('task')
    op.drop_index(op.f('ix_saml_config_is_active'), table_name='saml_config')
    op.drop_table('saml_config')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_oauth_credential_id'), table_name='oauth_credential')
    op.drop_table('oauth_credential')
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_document_document_id'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
