"""Updated knowledge base tables

Revision ID: a0dfba41ef64
Revises: 36703628c7a6
Create Date: 2025-04-24 17:30:04.147978

"""

from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a0dfba41ef64'
down_revision: Union[str, None] = '36703628c7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables if they exist
    op.drop_table('knowledge_base_embeddings', if_exists=True)
    op.drop_table('knowledge_base_documents', if_exists=True)
    op.drop_table('knowledge_bases', if_exists=True)

    # Create tables
    op.create_table(
        'knowledge_bases',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(
        op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False
    )
    op.create_table(
        'knowledge_base_documents',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('file_type', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_knowledge_base_documents_id'),
        'knowledge_base_documents',
        ['id'],
        unique=False,
    )
    op.create_table(
        'knowledge_base_embeddings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('document_id', sa.Uuid(), nullable=False),
        sa.Column('embedding_vector', pgvector.sqlalchemy.Vector(), nullable=True),
        sa.Column('chunk_text', sa.Text(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['document_id'], ['knowledge_base_documents.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_knowledge_base_embeddings_id'),
        'knowledge_base_embeddings',
        ['id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_knowledge_base_embeddings_id'), table_name='knowledge_base_embeddings'
    )
    op.drop_table('knowledge_base_embeddings')
    op.drop_index(
        op.f('ix_knowledge_base_documents_id'), table_name='knowledge_base_documents'
    )
    op.drop_table('knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
