"""add auth_secrets_table

Revision ID: 827b9d399023
Revises: b365be32ca72
Create Date: 2025-07-09 19:36:34.540004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827b9d399023'
down_revision: Union[str, None] = 'b365be32ca72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth_secrets',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_key', sa.String(), nullable=False),
        sa.Column('client_secret', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('client_key'),
    )
    op.create_index(op.f('ix_auth_secrets_id'), 'auth_secrets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_secrets_id'), table_name='auth_secrets')
    op.drop_table('auth_secrets')
    # ### end Alembic commands ###
