"""Updated the knowledge base tables for vector_size

Revision ID: b365be32ca72
Revises: 0da695688814
Create Date: 2025-06-11 19:37:24.072005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b365be32ca72'
down_revision: Union[str, None] = '0da695688814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'knowledge_bases', sa.Column('vector_size', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'vector_size')
    # ### end Alembic commands ###
