"""created the kb_inference table

Revision ID: 497a13558d60
Revises: d77dca43b31d
Create Date: 2025-05-02 13:00:14.942014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '497a13558d60'
down_revision: Union[str, None] = 'd77dca43b31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'knowledge_base_inferences',
        sa.Column('inference_id', sa.Uuid(), nullable=False),
        sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
        sa.Column('inference_content', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('inference_id'),
    )
    op.create_index(
        op.f('ix_knowledge_base_inferences_inference_id'),
        'knowledge_base_inferences',
        ['inference_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_knowledge_base_inferences_inference_id'),
        table_name='knowledge_base_inferences',
    )
    op.drop_table('knowledge_base_inferences')
    # ### end Alembic commands ###
