"""RBAC tables

Revision ID: 9b10292a95eb
Revises: 78655faf6488
Create Date: 2025-03-25 18:55:15.399620

"""

from typing import Sequence, Union
import uuid

from alembic import op
from db_repo_module.models.resource import ResourceScope
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9b10292a95eb'
down_revision: Union[str, None] = '78655faf6488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    op.execute("DELETE FROM role WHERE name != 'admin'")
    admin_rows = conn.execute(
        sa.text("SELECT * FROM role WHERE name = 'admin'")
    ).fetchall()

    admin_role_id = admin_rows[0].id

    user_rows = conn.execute(
        sa.text(f"SELECT * FROM public.user WHERE role_id = '{admin_role_id}'")
    ).fetchall()
    user_id = user_rows[0].id

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resource',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('scope', sa.String(), nullable=False),
        sa.Column('meta', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key', 'value', name='key_value'),
    )
    op.create_index(op.f('ix_resource_id'), 'resource', ['id'], unique=False)
    op.create_table(
        'role_resource',
        sa.Column('role_id', sa.String(), nullable=False),
        sa.Column('resource_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['resource_id'],
            ['resource.id'],
        ),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['role.id'],
        ),
        sa.PrimaryKeyConstraint('role_id', 'resource_id'),
    )
    op.create_table(
        'user_role',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('role_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['role.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('user_id', 'role_id'),
    )
    op.alter_column('notification', 'title', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('notification', 'type', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('role', 'description', existing_type=sa.VARCHAR(), nullable=True)
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE public.user SET deleted = false WHERE deleted IS NULL')
    op.alter_column('user', 'deleted', nullable=False)
    op.alter_column('user', 'email', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('user', 'password', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'team_id')

    ###
    admin_resource_id = uuid.uuid4()
    conn.execute(
        sa.text(
            """
            INSERT INTO resource (id, key, value, description, scope)
            VALUES (:id, :key, :value, :description, :scope)
        """
        ),
        [
            {
                'id': admin_resource_id,
                'key': 'console_resource',
                'value': 'admin_resource',
                'description': 'Admin resources for console',
                'scope': ResourceScope.CONSOLE,
            }
        ],
    )

    conn.execute(
        sa.text(
            f"INSERT INTO role_resource VALUES ('{admin_role_id}', '{admin_resource_id}')"
        )
    )

    conn.execute(
        sa.text(f"INSERT INTO user_role VALUES ('{user_id}', '{admin_role_id}')")
    )

    console_resources = [
        {
            'key': 'console_resource',
            'value': 'manager_resource',
            'description': 'Manager resources for console',
            'scope': ResourceScope.CONSOLE,
        },
        {
            'key': 'console_resource',
            'value': 'editor_resource',
            'description': 'Editor resources for console',
            'scope': ResourceScope.CONSOLE,
        },
        {
            'key': 'console_resource',
            'value': 'viewer_resource',
            'description': 'Viewer resources for console',
            'scope': ResourceScope.CONSOLE,
        },
        {
            'key': 'console_resource',
            'value': 'guest_resource',
            'description': 'Guest resources for console',
            'scope': ResourceScope.CONSOLE,
        },
    ]

    console_roles = [
        {
            'name': 'manager',
            'description': 'Manage users and perform CRUD operations; no config management',
        },
        {
            'name': 'editor',
            'description': 'Modify content; no user or config management',
        },
        {
            'name': 'viewer',
            'description': 'Read-only access; view data, no modifications',
        },
        {
            'name': 'guest',
            'description': 'Minimal access; view public/shared content only',
        },
    ]

    resources = []
    roles = []
    role_resources = []
    for i in range(0, len(console_resources)):
        resource_id = uuid.uuid4()
        res = console_resources[i]
        res['id'] = resource_id
        resources.append(res)

        role_id = uuid.uuid4()
        role = console_roles[i]
        role['id'] = role_id
        roles.append(role)

        role_resource = {'role_id': role_id, 'resource_id': resource_id}
        role_resources.append(role_resource)

    conn.execute(
        sa.text(
            """
            INSERT INTO resource (id, key, value, description, scope)
            VALUES (:id, :key, :value, :description, :scope)
        """
        ),
        resources,
    )

    conn.execute(
        sa.text(
            """
            INSERT INTO role (id, name, description)
            VALUES (:id, :name, :description)
        """
        ),
        roles,
    )

    conn.execute(
        sa.text(
            """
            INSERT INTO role_resource (role_id, resource_id)
            VALUES (:role_id, :resource_id)
        """
        ),
        role_resources,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'user', sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'password', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('user', 'email', existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column('user', 'deleted')
    op.alter_column('role', 'description', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('notification', 'type', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('notification', 'title', existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table('user_role')
    op.drop_table('role_resource')
    op.drop_index(op.f('ix_resource_id'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
