"""created model_inference table

Revision ID: f1f6e5c42780
Revises: 1aaf2b1e6d56
Create Date: 2025-08-24 07:17:31.968141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1f6e5c42780'
down_revision: Union[str, None] = '1aaf2b1e6d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'model_inference',
        sa.Column('model_id', sa.Uuid(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=True),
        sa.Column('model_path', sa.String(), nullable=True),
        sa.Column('model_type', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('model_id'),
        sa.UniqueConstraint('model_name'),
    )
    op.create_index(
        op.f('ix_model_inference_model_id'),
        'model_inference',
        ['model_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_inference_model_id'), table_name='model_inference')
    op.drop_table('model_inference')
    # ### end Alembic commands ###
