"""create_image_search_tables

Revision ID: bf901c107c8d
Revises: bb3907e50d30
Create Date: 2025-09-16 13:32:42.978978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bf901c107c8d'
down_revision: Union[str, None] = 'bb3907e50d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        'image_knowledge_bases',
        sa.Column('ikb_id', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('ikb_type', sa.String(length=50), nullable=False),
        sa.Column('algorithm_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('image_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('ikb_id'),
    )
    op.create_table(
        'reference_image_features',
        sa.Column('reference_image_id', sa.String(length=255), nullable=False),
        sa.Column('ikb_id', sa.String(length=255), nullable=True),
        sa.Column('algorithm_type', sa.String(length=50), nullable=False),
        sa.Column('image_url', sa.String(length=500), nullable=False),
        sa.Column('image_metadata', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['ikb_id'],
            ['image_knowledge_bases.ikb_id'],
        ),
        sa.PrimaryKeyConstraint('reference_image_id'),
    )
    op.create_table(
        'sift_features',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('reference_image_id', sa.String(length=255), nullable=False),
        sa.Column('keypoint_id', sa.Integer(), nullable=False),
        sa.Column('x', sa.Float(), nullable=False),
        sa.Column('y', sa.Float(), nullable=False),
        sa.Column('size', sa.Float(), nullable=False),
        sa.Column('angle', sa.Float(), nullable=False),
        sa.Column('response', sa.Float(), nullable=False),
        sa.Column('octave', sa.Integer(), nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=False),
        sa.Column('descriptor', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['reference_image_id'],
            ['reference_image_features.reference_image_id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic
    op.drop_table('sift_features')
    op.drop_table('reference_image_features')
    op.drop_table('image_knowledge_bases')
    # ### end Alembic commands ###
