"""create llm_inference_config table

Revision ID: 23db0be3a87a
Revises: f1f6e5c42780
Create Date: 2025-09-01 17:03:30.980177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '23db0be3a87a'
down_revision: Union[str, None] = 'f1f6e5c42780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'llm_inference_config',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('llm_model', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=False),
        sa.Column('api_key', sa.String(length=512), nullable=True),
        sa.Column('type', sa.String(length=64), nullable=False),
        sa.Column('base_url', sa.String(length=512), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_llm_inference_config_id'),
        'llm_inference_config',
        ['id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_inference_config_id'), table_name='llm_inference_config')
    op.drop_table('llm_inference_config')
    # ### end Alembic commands ###
