"""create_guardrail_policies_table

Revision ID: c3f8a91d42be
Revises: f8c2a91e4b07
Create Date: 2026-09-10 16:00:00.000000

Written by hand rather than autogenerated. Autogenerate run against a database
that is not at head emits a full-schema recreate - every existing table as a
CREATE TABLE - which fails on deploy and needs alembic_version patched by hand
afterwards.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3f8a91d42be'
down_revision: Union[str, None] = 'f8c2a91e4b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'guardrail_policies',
        sa.Column('namespace', sa.String(length=255), nullable=False),
        # Defaults are deliberately inert: a namespace that acquires a policy
        # row must not start blocking traffic until an admin turns it on.
        sa.Column(
            'is_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            'mode',
            sa.String(length=16),
            nullable=False,
            server_default='MONITOR',
        ),
        sa.Column(
            'policy_config',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='{}',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ['namespace'],
            ['namespaces.name'],
            name='fk_guardrail_policies_namespace',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('namespace', name='pk_guardrail_policies'),
    )


def downgrade() -> None:
    op.drop_table('guardrail_policies')
