"""create_guardrail_audit_events_table

Revision ID: a7e4b9c21d38
Revises: c3f8a91d42be
Create Date: 2026-09-15 11:00:00.000000

Written by hand rather than autogenerated, for the reason given in
c3f8a91d42be: autogenerate run against a database that is not at head emits a
full-schema recreate.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7e4b9c21d38'
down_revision: Union[str, None] = 'c3f8a91d42be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'guardrail_audit_events',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            nullable=False,
            server_default=sa.text('gen_random_uuid()'),
        ),
        # No foreign key to namespaces on purpose: audit rows must outlive the
        # things they describe, so deleting a namespace must not cascade away
        # the evidence of what happened in it.
        sa.Column('namespace', sa.String(length=255), nullable=False),
        sa.Column('agent_id', sa.String(length=255), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.Column('run_id', sa.String(length=128), nullable=True),
        sa.Column('stage', sa.String(length=32), nullable=False),
        sa.Column('action', sa.String(length=16), nullable=False),
        sa.Column('observed_action', sa.String(length=16), nullable=False),
        sa.Column('enforced', sa.Boolean(), nullable=False),
        sa.Column(
            'had_error',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column('policy_version', sa.String(length=64), nullable=True),
        # Findings only - adapter, code, severity, entity counts. Never the
        # evaluated content or the matched values.
        sa.Column(
            'findings',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='[]',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    # "What happened in this namespace recently" and "is the error rate
    # climbing" are the two queries this table exists to answer.
    op.create_index(
        'ix_guardrail_audit_namespace_created',
        'guardrail_audit_events',
        ['namespace', 'created_at'],
    )
    op.create_index(
        'ix_guardrail_audit_had_error_created',
        'guardrail_audit_events',
        ['had_error', 'created_at'],
    )


def downgrade() -> None:
    op.drop_index(
        'ix_guardrail_audit_had_error_created', table_name='guardrail_audit_events'
    )
    op.drop_index(
        'ix_guardrail_audit_namespace_created', table_name='guardrail_audit_events'
    )
    op.drop_table('guardrail_audit_events')
