from dotenv import load_dotenv
import os

load_dotenv()

CLOUD_PROVIDER = os.getenv('CLOUD_PROVIDER', 'gcp')
CLOUD_REGION = os.getenv('CLOUD_REGION')
CLOUD_PROJECT_ID = os.getenv('CLOUD_PROJECT_ID')
CLOUD_LOCATION = os.getenv('CLOUD_LOCATION')

RAG_QUEUE = os.getenv('RAG_QUEUE')
RAG_QUEUE_SUBSCRIPTION = os.getenv('RAG_QUEUE_SUBSCRIPTION')
AZURE_STORAGE_ACCOUNT_URL = os.getenv('AZURE_STORAGE_ACCOUNT_URL')

KMS_KEY_RING = os.getenv('KMS_KEY_RING')
KMS_ENCRYPTION_KEY = os.getenv('KMS_ENCRYPTION_KEY')
KMS_ENCRYPTION_KEY_VERSION = os.getenv('KMS_ENCRYPTION_KEY_VERSION')
AZURE_KEY_VAULT_URL = os.getenv('AZURE_KEY_VAULT_URL')
AZURE_CLIENT_ID = os.getenv('AZURE_CLIENT_ID')
AZURE_CLIENT_SECRET = os.getenv('AZURE_CLIENT_SECRET')
AZURE_TENANT_ID = os.getenv('AZURE_TENANT_ID')

REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_PROTOCOL = os.getenv('REDIS_PROTOCOL', 'redis')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')
REDIS_DB = os.getenv('REDIS_DB', '0')

RETRY_COUNT = os.getenv('RETRY_COUNT', 3)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
EMBEDDING_SERVICE_URL = os.getenv('EMBEDDING_SERVICE_URL')
INFERENCE_SERVICE_URL = os.getenv('INFERENCE_SERVICE_URL')
FLOWARE_SERVICE_URL = os.getenv('FLOWARE_SERVICE_URL')
APP_ENV = os.getenv('APP_ENV', 'dev')
PASSTHROUGH_SECRET = os.getenv('PASSTHROUGH_SECRET')
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'text-embedding-3-small')
STREAMING_BATCH_SIZE = int(os.getenv('STREAMING_BATCH_SIZE', 100))
