name: Security Report

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat_git_report_workflow'

jobs:
  generate-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write # Required to fetch CodeQL/Dependabot alerts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python, javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python,javascript"
          upload: false # Disable upload to avoid conflict with default setup

      # Required for some PDF renderers used in these actions
      - name: Install browser for PDF generation
        run: npx puppeteer browsers install chrome

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Generate Security Report
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Explicitly set if files aren't found in root
          # sarifReportDir: ../results 
          puppeteerLaunchArgs: "--no-sandbox --disable-setuid-sandbox" 

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report-${{ steps.date.outputs.date }}
          path: |
            summary.pdf
            summary.html
          if-no-files-found: error # Fast-fail if the report wasn't generated
